### ISSUE TITLE
make a ssb package repo

### ISSUE THREAD

**Issue by Jonathan7SSB** [statisticsnorway/ssb-project-cli#262]
It would be nice to let ssb-project make a python package repo according to SSB standards and necessities for the developers. ssb-project can be used already, but we should use some best practice when it comes to setting version numbers for the package and let this be a part of github workflow! So this would be another template to use specific for package repos.

example for use:
ssb-project create my-package --github --package
-> creates repo ssb-my-package

**Comment by mmwinther** [comment]
Hi @Jonathan7SSB, thanks for the great suggestion! This is actually possible with v1.2.0, since it allows specifying any Cookiecutter template. There is a template for PyPI packages in SSB under development, so you can use a command like `ssb-project create my-package --template-git-url https://github.com/statisticsnorway/ssb-pypitemplate` to do this.
